SELECT
	MEI.EIGYOUSYO_CODE,
	MEI.EIGYOUSYO_NAME,
	MEI.EIGYOUSYO_KANA,
	MEI.EIGYOUSYO_YUUBIN,
	MEI.EIGYOUSYO_JYUUSYO,
	MEI.EIGYOUSYO_TATEMONO_NAME,
	MEI.EIGYOUSYO_TEL,
	MEI.EIGYOUSYO_FAX,
	MEI.EIGYOUSYO_GROUP_CODE,
	MGE.TORIHIKI_STATUS
FROM
	M_GYOUSYA_EIGYOUSYO MGE
INNER JOIN M_EIGYOUSYO MEI ON MGE.EIGYOUSYO_CODE = MEI.EIGYOUSYO_CODE
WHERE
	MGE.GYOUSYA_CODE = /*gyousyaCode*/1 AND
	MGE.TORIHIKI_STATUS = '0'
	/*%if eigyousyoGroupCode != null && eigyousyoGroupCode != ""*/
	AND MEI.EIGYOUSYO_GROUP_CODE = /*eigyousyoGroupCode*/1
	/*%end*/
ORDER BY
	MEI.EIGYOUSYO_KANA COLLATE utf8_unicode_ci ASC;