SELECT * FROM V_ORDER_ITEM
WHERE DENPYOU_NO IN
(
SELECT DENPYOU_NO FROM V_ORDER
WHERE
/*%if prevDate != null*/
SAISYUU_KOUSIN_DATE >= /*prevDate*/'2019-08-01'
/*%end*/
)
ORDER BY DENPYOU_NO, MEISAI_SEQ_NO
;