SELECT
	MSY.*
FROM
	M_SYAIN_EIGYOUSYO MSE
INNER JOIN M_SYAIN MSY ON MSE.SYAIN_CODE = MSY.SYAIN_CODE
WHERE
	MSE.EIGYOUSYO_CODE = /*eigyousyoCode*/0
	AND MSY.SYOKUSYU_FLG = '3'
	AND MSY.TAISYOKU_FLG = 0
ORDER BY
	MSY.SYAIN_KANA COLLATE utf8_unicode_ci ASC;